FROM eclipse-temurin:17-jre-jammy
RUN useradd --system --uid 10001 --home /var/lib/hfg --shell /usr/sbin/nologin hfg && mkdir -p /app /etc/hfg/pki /var/lib/hfg && chown -R hfg:hfg /app /var/lib/hfg
COPY hfg-gateway-app/target/hfg-gateway-app-*.jar /app/hfg-gateway.jar
USER 10001
EXPOSE 21 22 18080 30000-31000
ENTRYPOINT ["java","-XX:MaxRAMPercentage=75","-Djava.security.egd=file:/dev/urandom","-jar","/app/hfg-gateway.jar"]
