FROM --platform=linux/amd64 eclipse-temurin:17-jre-jammy
LABEL org.opencontainers.image.title="HFG Gateway" \
      org.opencontainers.image.version="0.1.3" \
      org.opencontainers.image.architecture="amd64"
RUN useradd --system --uid 10001 --home /var/lib/hfg --shell /usr/sbin/nologin hfg \
    && install -d -o hfg -g hfg /app /var/lib/hfg /etc/hfg/pki
COPY --chown=hfg:hfg bin/hfg-gateway.jar /app/hfg-gateway.jar
USER 10001
EXPOSE 21 22 18080 30000-31000
ENTRYPOINT ["java","-XX:MaxRAMPercentage=75","-Djava.security.egd=file:/dev/urandom","-jar","/app/hfg-gateway.jar"]
