FROM --platform=linux/amd64 eclipse-temurin:17-jre-jammy
LABEL org.opencontainers.image.title="HFG Manager" \
      org.opencontainers.image.version="0.1.7" \
      org.opencontainers.image.architecture="amd64"
RUN useradd --system --uid 10001 --home /var/lib/hfg --shell /usr/sbin/nologin hfg \
    && install -d -o hfg -g hfg /app /var/lib/hfg /etc/hfg/pki
COPY --chown=hfg:hfg bin/hfg-manager.jar /app/hfg-manager.jar
USER 10001
EXPOSE 8080 19090
ENTRYPOINT ["java","-XX:MaxRAMPercentage=75","-Djava.security.egd=file:/dev/urandom","-jar","/app/hfg-manager.jar"]
