<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion><parent><groupId>io.github.scholiarw.hfg</groupId><artifactId>hfg-parent</artifactId><version>0.1.6</version></parent>
  <artifactId>hfg-manager-domain</artifactId><name>HFG :: Manager Domain</name>
  <dependencies>
    <dependency><groupId>io.github.scholiarw.hfg</groupId><artifactId>hfg-common-contract</artifactId></dependency>
    <dependency><groupId>org.junit.jupiter</groupId><artifactId>junit-jupiter</artifactId><scope>test</scope></dependency>
  </dependencies>
</project>
