export type AccountStatus='ENABLED'|'DISABLED'|'LOCKED'|'EXPIRED';
export interface User{id:string;username:string;department?:string;businessDomain?:string;phone?:string;email?:string;note?:string;status:AccountStatus;serviceGroupId:string;expiresAt?:string;createdAt:string;updatedAt:string;revision:number}
export interface Page<T>{items:T[];total:number;page:number;size:number}
const AUTH_KEY='hfg.authorization';
export interface AuthenticatedAdmin{username:string;roles:string[]}
function authorization(username:string,password:string){return'Basic '+btoa(`${username}:${password}`)}
export function setCredentials(username:string,password:string){sessionStorage.setItem(AUTH_KEY,authorization(username,password));}
export function clearCredentials(){sessionStorage.removeItem(AUTH_KEY)}
export function hasCredentials(){return Boolean(sessionStorage.getItem(AUTH_KEY))}
export async function authenticate(username:string,password:string):Promise<AuthenticatedAdmin>{const header=authorization(username,password);let response:Response;try{response=await fetch('/api/v1/auth/me',{headers:{Authorization:header,Accept:'application/json'}})}catch{throw new Error('无法连接 Manager，请检查网络或服务状态')}if(response.status===401)throw new Error('用户名或密码错误');if(response.status===403)throw new Error('当前账号没有管理权限');if(!response.ok)throw new Error(`Manager 服务异常（HTTP ${response.status}）`);const admin=await response.json() as AuthenticatedAdmin;setCredentials(username,password);return admin}
function authorizedHeaders(init:RequestInit){const headers=new Headers(init.headers),auth=sessionStorage.getItem(AUTH_KEY);if(auth)headers.set('Authorization',auth);return headers}
export async function api<T>(path:string,init:RequestInit={}):Promise<T>{const headers=authorizedHeaders(init);headers.set('Accept','application/json');if(init.body&&!(init.body instanceof FormData))headers.set('Content-Type','application/json');const response=await fetch(path,{...init,headers});if(response.status===401){clearCredentials();location.assign('/login');throw new Error('登录已失效')}if(!response.ok){const body=await response.json().catch(()=>({detail:response.statusText}));throw new Error(body.detail||body.title||'请求失败')}return response.status===204?undefined as T:response.json()}
export async function download(path:string,body:unknown,filename:string){const response=await fetch(path,{method:'POST',headers:authorizedHeaders({headers:{'Content-Type':'application/json'}}),body:JSON.stringify(body)});if(!response.ok){if(response.status===401){clearCredentials();location.assign('/login');throw new Error('登录已失效')}const problem=await response.json().catch(()=>({detail:response.statusText}));throw new Error(`${problem.detail||problem.title||'下载失败'}（HTTP ${response.status}）`)}const url=URL.createObjectURL(await response.blob()),link=document.createElement('a');link.href=url;link.download=filename;link.click();URL.revokeObjectURL(url)}
export const users={list:(page=0,size=20,query='')=>api<Page<User>>(`/api/v1/users?page=${page}&size=${size}&query=${encodeURIComponent(query)}`),create:(body:unknown)=>api<User>('/api/v1/users',{method:'POST',body:JSON.stringify(body)}),update:(u:User,body:unknown)=>api<User>(`/api/v1/users/${u.id}`,{method:'PUT',headers:{'If-Match':String(u.revision)},body:JSON.stringify(body)}),status:(u:User,status:AccountStatus)=>api<User>(`/api/v1/users/${u.id}/status`,{method:'PUT',headers:{'If-Match':String(u.revision)},body:JSON.stringify({status})}),resetPassword:(u:User,password:string)=>api<void>(`/api/v1/users/${u.id}/password`,{method:'PUT',headers:{'If-Match':String(u.revision)},body:JSON.stringify({password})}),remove:(id:string)=>api<void>(`/api/v1/users/${id}`,{method:'DELETE'})};
export const hdfs={create:(id:string,name:string,file:File)=>{const form=new FormData();form.set('id',id);form.set('name',name);form.set('file',file);return api<Record<string,unknown>>('/api/v1/system/hdfs-clusters/import',{method:'POST',body:form})},reupload:(id:string,file:File)=>{const form=new FormData();form.set('file',file);return api<Record<string,unknown>>(`/api/v1/system/hdfs-clusters/${id}/authentication`,{method:'PUT',body:form})},remove:(id:string)=>api<void>(`/api/v1/system/hdfs-clusters/${id}`,{method:'DELETE'})};
export function formatBytes(value:number){if(!Number.isFinite(value)||value<0)return'-';if(value===0)return'0 B';const units=['B','KiB','MiB','GiB','TiB','PiB'];const i=Math.min(Math.floor(Math.log(value)/Math.log(1024)),units.length-1);return`${(value/1024**i).toFixed(i===0?0:2)} ${units[i]}`}
export function snapshotVersion(envelope:Record<string,unknown>){try{return Number(JSON.parse(String(envelope.payloadJson)).version||0)}catch{return 0}}
