export type AccountStatus='ENABLED'|'DISABLED'|'LOCKED'|'EXPIRED';
export interface User{id:string;username:string;department?:string;businessDomain?:string;phone?:string;email?:string;note?:string;status:AccountStatus;serviceGroupId:string;hdfsEffectiveUser?:string;expiresAt?:string;createdAt:string;updatedAt:string;revision:number}
export interface Page<T>{items:T[];total:number;page:number;size:number}
const AUTH_KEY='hfg.authorization';
export function setCredentials(username:string,password:string){sessionStorage.setItem(AUTH_KEY,'Basic '+btoa(`${username}:${password}`));}
export function clearCredentials(){sessionStorage.removeItem(AUTH_KEY)}
export function hasCredentials(){return Boolean(sessionStorage.getItem(AUTH_KEY))}
export async function api<T>(path:string,init:RequestInit={}):Promise<T>{const headers=new Headers(init.headers);headers.set('Accept','application/json');if(init.body)headers.set('Content-Type','application/json');const auth=sessionStorage.getItem(AUTH_KEY);if(auth)headers.set('Authorization',auth);const response=await fetch(path,{...init,headers});if(response.status===401){clearCredentials();location.assign('/login');throw new Error('登录已失效')}if(!response.ok){const body=await response.json().catch(()=>({detail:response.statusText}));throw new Error(body.detail||body.title||'请求失败')}return response.status===204?undefined as T:response.json()}
export const users={list:(page=0,size=20,query='')=>api<Page<User>>(`/api/v1/users?page=${page}&size=${size}&query=${encodeURIComponent(query)}`),create:(body:unknown)=>api<User>('/api/v1/users',{method:'POST',body:JSON.stringify(body)}),update:(u:User,body:unknown)=>api<User>(`/api/v1/users/${u.id}`,{method:'PUT',headers:{'If-Match':String(u.revision)},body:JSON.stringify(body)}),status:(u:User,status:AccountStatus)=>api<User>(`/api/v1/users/${u.id}/status`,{method:'PUT',headers:{'If-Match':String(u.revision)},body:JSON.stringify({status})}),resetPassword:(u:User,password:string)=>api<void>(`/api/v1/users/${u.id}/password`,{method:'PUT',headers:{'If-Match':String(u.revision)},body:JSON.stringify({password})}),remove:(id:string)=>api<void>(`/api/v1/users/${id}`,{method:'DELETE'})};
export function formatBytes(value:number){if(!Number.isFinite(value)||value<0)return'-';if(value===0)return'0 B';const units=['B','KiB','MiB','GiB','TiB','PiB'];const i=Math.min(Math.floor(Math.log(value)/Math.log(1024)),units.length-1);return`${(value/1024**i).toFixed(i===0?0:2)} ${units[i]}`}
export function snapshotVersion(envelope:Record<string,unknown>){try{return Number(JSON.parse(String(envelope.payloadJson)).version||0)}catch{return 0}}
