import {useEffect,useState} from 'react';
import {Button,Card,Form,Input,Modal,Space,Table,Tag,Toast,Typography} from '@douyinfe/semi-ui';
import {IconDelete,IconPlus,IconRefresh} from '@douyinfe/semi-icons';
import {api,download,gatewayStatus,hdfs,snapshotVersion} from './api';

const {Title,Text}=Typography;
type Row=Record<string,unknown>;

function Header({title,description,actions}:{title:string;description:string;actions?:React.ReactNode}){
 return <div className="page-header"><div><Title heading={4}>{title}</Title><Text type="tertiary">{description}</Text></div><Space wrap>{actions}</Space></div>;
}
function errorMessage(error:unknown){return error instanceof Error?error.message:String(error)}
function confirmAction(title:string,content:string,action:()=>Promise<void>){Modal.confirm({title,content,okText:'确认',cancelText:'取消',onOk:action})}
const rowSelection=(selected:string[],setSelected:(keys:string[])=>void)=>({selectedRowKeys:selected,onChange:(keys:(string|number)[]|undefined)=>setSelected((keys||[]).map(String))});

export function Monitoring(){
 const[result,setResult]=useState(''),[query,setQuery]=useState('sum(jvm_memory_used_bytes{area="heap"}) by (application)'),[rules,setRules]=useState<Row[]>([]),[channels,setChannels]=useState<Row[]>([]),[ruleOpen,setRuleOpen]=useState(false),[channelOpen,setChannelOpen]=useState(false),[prometheus,setPrometheus]=useState<Row>({});
 async function load(){const[ruleRows,channelRows]=await Promise.all([api<Row[]>('/api/v1/alerts/rules'),api<Row[]>('/api/v1/alerts/channels')]);setRules(ruleRows);setChannels(channelRows)}
 useEffect(()=>{void load().catch(error=>Toast.error(errorMessage(error)));void api<Row>('/api/v1/monitoring/status').then(setPrometheus).catch(()=>setPrometheus({enabled:false}))},[]);
 async function run(){try{setResult(JSON.stringify(await api(`/api/v1/monitoring/query?query=${encodeURIComponent(query)}`),null,2))}catch(error){Toast.error(errorMessage(error))}}
 return <>
  <Header title="监控告警" description="查询 JVM、进程和连接池运行指标，并维护告警规则和通知渠道" actions={<><Button onClick={()=>setChannelOpen(true)}>添加渠道</Button><Button onClick={()=>setRuleOpen(true)}>添加规则</Button><Button theme="solid" disabled={!prometheus.enabled} onClick={run}>执行查询</Button></>}/>
  <Card title="PromQL" className="section-card"><Space><Tag color={prometheus.enabled?(prometheus.reachable?'green':'amber'):'grey'}>{prometheus.enabled?(prometheus.reachable?'已开启':'已开启但不可达'):'未开启'}</Tag><Text type="tertiary">{String(prometheus.message||'')}</Text></Space>{prometheus.enabled?<><Input value={query} onChange={setQuery}/><pre className="result">{result||'执行查询后显示结果'}</pre></>:<div className="empty-state">Prometheus 功能未开启，如需使用请配置 HFG_PROMETHEUS_ENABLED=true 与 HFG_PROMETHEUS_URL 后重启 Manager。</div>}</Card>
  <div className="two-col"><Card title="告警规则"><Table size="small" pagination={false} dataSource={rules} columns={[{title:'名称',dataIndex:'name'},{title:'级别',dataIndex:'severity'},{title:'持续秒数',dataIndex:'duration_seconds'},{title:'状态',dataIndex:'enabled',render:(value:boolean)=><Tag color={value?'green':'grey'}>{value?'启用':'停用'}</Tag>}]}/></Card><Card title="告警渠道"><Table size="small" pagination={false} dataSource={channels} columns={[{title:'名称',dataIndex:'name'},{title:'类型',dataIndex:'channel_type'},{title:'Secret 引用',dataIndex:'config_secret_ref'},{title:'状态',dataIndex:'enabled',render:(value:boolean)=><Tag color={value?'green':'grey'}>{value?'启用':'停用'}</Tag>}]}/></Card></div>
  <Modal title="添加告警规则" visible={ruleOpen} footer={null} onCancel={()=>setRuleOpen(false)}><Form labelPosition="top" onSubmit={async values=>{try{await api('/api/v1/alerts/rules',{method:'POST',body:JSON.stringify({...values,durationSeconds:Number(values.durationSeconds),labelsJson:'{}',annotationsJson:'{}',enabled:true})});setRuleOpen(false);await load()}catch(error){Toast.error(errorMessage(error))}}}><Form.Input field="name" label="名称" rules={[{required:true}]}/><Form.TextArea field="promql" label="PromQL" rules={[{required:true}]}/><div className="form-grid"><Form.InputNumber field="durationSeconds" label="持续秒数" initValue={300}/><Form.Select field="severity" label="级别" initValue="warning" optionList={[{label:'warning',value:'warning'},{label:'critical',value:'critical'}]}/></div><Button htmlType="submit" theme="solid" block>保存</Button></Form></Modal>
  <Modal title="添加告警渠道" visible={channelOpen} footer={null} onCancel={()=>setChannelOpen(false)}><Form labelPosition="top" onSubmit={async values=>{try{await api('/api/v1/alerts/channels',{method:'POST',body:JSON.stringify({...values,enabled:true})});setChannelOpen(false);await load()}catch(error){Toast.error(errorMessage(error))}}}><Form.Input field="name" label="名称" rules={[{required:true}]}/><Form.Select field="channelType" label="类型" optionList={['EMAIL','WEBHOOK','SLACK','PAGERDUTY'].map(value=>({label:value,value}))} rules={[{required:true}]}/><Form.Input field="configSecretRef" label="Secret 引用" placeholder="vault://hfg/alerts/primary" rules={[{required:true}]}/><Button htmlType="submit" theme="solid" block>保存</Button></Form></Modal>
 </>;
}

export function SystemPage(){
 const[clusters,setClusters]=useState<Row[]>([]),[groups,setGroups]=useState<Row[]>([]),[gateways,setGateways]=useState<Row[]>([]),[snapshots,setSnapshots]=useState<Record<string,number>>({}),[selectedClusters,setSelectedClusters]=useState<string[]>([]),[selectedGroups,setSelectedGroups]=useState<string[]>([]);
 const[clusterOpen,setClusterOpen]=useState(false),[groupOpen,setGroupOpen]=useState(false),[certificateOpen,setCertificateOpen]=useState(false),[certificateError,setCertificateError]=useState(''),[hdfsZip,setHdfsZip]=useState<File>(),[reupload,setReupload]=useState<Row>(),[reuploadZip,setReuploadZip]=useState<File>(),[busy,setBusy]=useState(false);
 async function load(){const[clusterRows,groupRows,nodeRows]=await Promise.all([api<Row[]>('/api/v1/system/hdfs-clusters'),api<Row[]>('/api/v1/system/service-groups'),api<Row[]>('/api/v1/system/gateways')]);setClusters(clusterRows);setGroups(groupRows);setGateways(nodeRows);setSelectedClusters([]);setSelectedGroups([]);const versions=await Promise.all(groupRows.map(async row=>{try{const snapshot=await api<Row>(`/api/v1/control/snapshots/${row.id}/latest`);return[String(row.id),snapshotVersion(snapshot)] as const}catch{return[String(row.id),0] as const}}));setSnapshots(Object.fromEntries(versions))}
 useEffect(()=>{void load().catch(error=>Toast.error(errorMessage(error)))},[]);
 const selectedCluster=clusters.find(row=>String(row.id)===selectedClusters[0]);
 async function publishSelected(){try{for(const id of selectedGroups){const snapshot=await api<Row>(`/api/v1/control/snapshots/${id}/publish`,{method:'POST'});setSnapshots(value=>({...value,[id]:snapshotVersion(snapshot)}))}Toast.success(`已强制发布 ${selectedGroups.length} 个服务组`)}catch(error){Toast.error(errorMessage(error))}}
 async function deleteClusters(){try{for(const id of selectedClusters)await hdfs.remove(id);Toast.success('所选 HDFS 连接已删除');await load()}catch(error){Toast.error(errorMessage(error));await load()}}
 async function deleteGroups(){try{for(const id of selectedGroups)await api(`/api/v1/system/service-groups/${id}`,{method:'DELETE'});Toast.success('所选服务组已删除');await load()}catch(error){Toast.error(errorMessage(error));await load()}}
 const clusterColumns=[{title:'名称',dataIndex:'name'},{title:'Default FS',dataIndex:'default_fs'},{title:'Nameservice',dataIndex:'nameservice'},{title:'Keytab Principal',dataIndex:'principal'},{title:'认证文件',dataIndex:'bundle_available',render:(value:boolean)=>value?<Tag color="green">已上传</Tag>:<Tag color="red">文件缺失</Tag>},{title:'配置包 SHA-256',dataIndex:'bundle_sha256',render:(value:string)=>value?String(value).slice(0,16)+'…':'-'},{title:'状态',dataIndex:'status',render:(value:unknown)=><Tag color={value==='ENABLED'?'green':'grey'}>{String(value)}</Tag>}];
 const groupColumns=[{title:'名称',dataIndex:'name'},{title:'VIP',dataIndex:'vip'},{title:'HDFS 集群',dataIndex:'hdfs_cluster_id'},{title:'状态',dataIndex:'status'},{title:'已发布快照',render:(_:unknown,row:Row)=>snapshots[String(row.id)]?`v${snapshots[String(row.id)]}`:'等待自动发布'}];
 return <>
  <Header title="系统管理" description="勾选 HDFS 连接或服务组后，在顶部执行重新上传、强制发布和删除操作" actions={<><Button icon={<IconRefresh/>} onClick={load}/><Button onClick={()=>setCertificateOpen(true)}>生成 Gateway 证书</Button><Button icon={<IconPlus/>} onClick={()=>setClusterOpen(true)}>新建 HDFS 连接</Button><Button disabled={selectedClusters.length!==1} onClick={()=>{setReuploadZip(undefined);setReupload(selectedCluster)}}>重传 HDFS 认证包</Button><Button type="danger" icon={<IconDelete/>} disabled={!selectedClusters.length} onClick={()=>confirmAction('删除所选 HDFS 连接',`将删除 ${selectedClusters.length} 个连接。存在服务组或目录引用时会拒绝删除。`,deleteClusters)}>删除 HDFS 连接</Button><Button theme="solid" icon={<IconPlus/>} onClick={()=>setGroupOpen(true)}>添加服务组</Button><Button disabled={!selectedGroups.length} onClick={()=>void publishSelected()}>强制发布配置</Button><Button type="danger" icon={<IconDelete/>} disabled={!selectedGroups.length} onClick={()=>confirmAction('删除所选服务组',`将删除 ${selectedGroups.length} 个服务组。在线 Gateway、用户或目录关联会阻止删除。`,deleteGroups)}>删除服务组</Button></>}/>
  <Card title="HDFS 接入" className="section-card"><Table rowKey="id" rowSelection={rowSelection(selectedClusters,setSelectedClusters)} pagination={false} dataSource={clusters} columns={clusterColumns}/></Card>
  <Card title="VIP 服务组" className="section-card"><Table rowKey="id" rowSelection={rowSelection(selectedGroups,setSelectedGroups)} pagination={false} dataSource={groups} columns={groupColumns}/></Card>
  <Card title="Gateway 节点"><Table rowKey="id" dataSource={gateways} columns={[{title:'节点',dataIndex:'hostname'},{title:'IP',dataIndex:'ip_address'},{title:'FTP',dataIndex:'ftp_port'},{title:'SFTP',dataIndex:'sftp_port'},{title:'管理端口',dataIndex:'management_port'},{title:'服务组',dataIndex:'service_group_id'},{title:'版本',dataIndex:'software_version'},{title:'快照版本',dataIndex:'snapshot_version'},{title:'最后心跳',dataIndex:'last_heartbeat_at',render:(value:string)=>value?new Date(value).toLocaleString():'-'},{title:'状态',dataIndex:'status',render:(value:string)=>{const status=gatewayStatus(value);return <Tag color={status.color}>{status.label}</Tag>}},{title:'运行错误',dataIndex:'last_error',render:(value:string)=>value||'-'}]}/></Card>
  <Modal title="新建或覆盖 HDFS 连接" visible={clusterOpen} footer={null} onCancel={()=>setClusterOpen(false)}><Form labelPosition="top" onSubmit={async values=>{if(!hdfsZip){Toast.error('请选择 ZIP 文件');return}try{setBusy(true);await hdfs.create(String(values.id),String(values.name),hdfsZip);setClusterOpen(false);setHdfsZip(undefined);Toast.success('配置已解析并生效');await load()}catch(error){Toast.error(errorMessage(error))}finally{setBusy(false)}}}><Form.Input field="id" label="标识" rules={[{required:true}]}/><Form.Input field="name" label="名称" rules={[{required:true}]}/><label>HDFS 配置 ZIP（XML + Keytab）</label><input type="file" accept=".zip,application/zip" onChange={event=>setHdfsZip(event.target.files?.[0])}/><Button htmlType="submit" theme="solid" block loading={busy}>上传并解析</Button></Form></Modal>
  <Modal title={`重新上传认证文件：${String(reupload?.name||'')}`} visible={Boolean(reupload)} footer={null} onCancel={()=>{setReupload(undefined);setReuploadZip(undefined)}}><Form key={String(reupload?.id||'')} labelPosition="top" onSubmit={async()=>{if(!reuploadZip){Toast.error('请选择 ZIP 文件');return}try{setBusy(true);await hdfs.reupload(String(reupload?.id),reuploadZip);setReupload(undefined);setReuploadZip(undefined);Toast.success('认证文件已更新');await load()}catch(error){Toast.error(errorMessage(error))}finally{setBusy(false)}}}><Form.Input field="id" label="标识" initValue={String(reupload?.id||'')} disabled/><label>新的 HDFS 配置 ZIP（XML + Keytab）</label><input type="file" accept=".zip,application/zip" onChange={event=>setReuploadZip(event.target.files?.[0])}/><Button htmlType="submit" theme="solid" block loading={busy}>上传并替换</Button></Form></Modal>
  <Modal title="生成 Gateway 客户端证书" visible={certificateOpen} footer={null} onCancel={()=>setCertificateOpen(false)}><Form labelPosition="top" onSubmit={async values=>{try{setCertificateError('');await download('/api/v1/system/gateway-certificates',values,`${values.gatewayId}-certificate.zip`);setCertificateOpen(false);Toast.success('证书包已生成')}catch(error){const message=errorMessage(error);setCertificateError(message);Toast.error(message)}}}><Form.Input field="gatewayId" label="Gateway 标识" rules={[{required:true}]}/><Form.Select field="serviceGroupId" label="服务组" optionList={groups.map(group=>({label:String(group.name),value:String(group.id)}))} rules={[{required:true}]}/><Button htmlType="submit" theme="solid" block>生成并下载</Button>{certificateError&&<Text type="danger">{certificateError}</Text>}</Form></Modal>
  <Modal title="添加服务组" visible={groupOpen} footer={null} onCancel={()=>setGroupOpen(false)}><Form labelPosition="top" onSubmit={async values=>{try{setBusy(true);await api('/api/v1/system/service-groups',{method:'POST',body:JSON.stringify(values)});setGroupOpen(false);Toast.success('服务组已创建');await load()}catch(error){Toast.error(errorMessage(error))}finally{setBusy(false)}}}><Form.Input field="id" label="标识" rules={[{required:true}]}/><Form.Input field="name" label="名称" rules={[{required:true}]}/><Form.Input field="vip" label="VIP" rules={[{required:true}]}/><Form.Select field="hdfsClusterId" label="HDFS 集群" optionList={clusters.map(cluster=>({label:String(cluster.name),value:String(cluster.id)}))} rules={[{required:true}]}/><Button htmlType="submit" theme="solid" block loading={busy}>保存</Button></Form></Modal>
 </>;
}
