package io.github.scholiarw.hfg.contract;

public enum HfgErrorCode {
  AUTH_INVALID,
  ACCOUNT_DISABLED,
  PATH_NOT_FOUND,
  PERMISSION_DENIED,
  ALREADY_EXISTS,
  QUOTA_EXCEEDED,
  RATE_LIMITED,
  UNSUPPORTED_OFFSET,
  HDFS_UNAVAILABLE,
  INVALID_PATH,
  CONFIG_INVALID,
  INTERNAL_ERROR
}
